### ISSUE TITLE
Add Survey questions

### ISSUE THREAD

**Issue by bencrosier** [jefferythewind/arra#34]
Please add the following five survey questions:

1. Do you feel happy in general?
-Strongly Agree 
-Agree
-Neutral
-Disagree
-Strongly Disagree

2. In the last year, have you experienced (_select all that apply_):
-A breakup
-End of a major friendship
-Death of a loved one
-Other serious loss

3. To what extent do you agree with this statement: “I am a narcissist.” (Note: The word “narcissist” means egotistical, self-focused, and vain.)
-Strongly Agree 
-Agree
-Neutral
-Disagree
-Strongly Disagree

4. I feel out of control in the presence of delicious food. 
-Strongly Agree 
-Agree
-Neutral
-Disagree
-Strongly Disagree

5. When I start eating, I just can’t seem to stop.
-Strongly Agree 
-Agree
-Neutral
-Disagree
-Strongly Disagree

**Comment by jefferythewind** [comment]
We consolidated the 2 food questions
